### ISSUE TITLE
How to set the End timestamp correctly?

### ISSUE THREAD

**Issue by Joe112Carlos** [Lachee/discord-rpc-csharp#42]
Hi!
 I know this isn`t really an issue, anyways ive been trying to set the "Time Left" ( 00:00 Left) Thingy and it always says 00:00 Left when i try it.
Defining the time when its over:
``            DateTime timeover = new DateTime(DateTime.UtcNow.Year, DateTime.UtcNow.Month, DateTime.UtcNow.Day, DateTime.UtcNow.Hour + Hours, DateTime.UtcNow.Minute + Minutes, DateTime.UtcNow.Second + 10); 
``
Setting Timestamps:

` Timestamps = new DiscordRPC.Timestamps()
                    {
                        Start = DateTime.UtcNow,
                        End = timeover                       
                    }`

Hours and Minutes are an Int defined by a NumericUpDown

**Comment by Lachee** [comment]
Sorry, this issue was fixed a few commits ago but the fixed caused a issue further down the line with Discord returning unexpected values back for the time (see issue https://github.com/discordapp/discord-rpc/issues/231 ). This has since been fixed in this library and you will just need to update your build.

Originally discord would also only display "Remaining" when `start` was set to null, but that seems to been fixed now too. If you are still experiencing issues after updating, try and set the start time to `null` too see if it fixes it.

Cheers

**Comment by Joe112Carlos** [comment]
Thanks again! :)
