### ISSUE TITLE
64bit support?

### ISSUE THREAD

**Issue by Agrair** [Lachee/discord-rpc-csharp#52]
Does this repository support 64bit? And when mono is supported, do you think, in theory, that mono 64bit will be supported as well? Not really necessary, but it's something a friend is interested in for the 64bit version he built.

**Comment by Lachee** [comment]
It's 64bit supported. It's compiled under AnyCpu by default so it should work. If you have troubles you can always recompile it manually yourself. 

Yes it should work with mono as it works with Unity3D. 

The unity package is 64bit only by default too, because I was too lazy to build 32bit binaries.

**Comment by Agrair** [comment]
Oh, thanks!

Btw, where *are* the prebuilt binaries? Since you have no releases.

**Comment by Agrair** [comment]
Wait never mind.
